import { readFileSync } from "node:fs";
let s = readFileSync("src/channels/chatplus.js", "utf8");
let lines = s.split("\n");
let i = lines.findIndex(l => l.includes("function splitHttp"));
for (let j = i; j < i + 30; j++) console.log(j + 1, lines[j]);
console.log("---- setCookiesFromHeaders ----");
i = lines.findIndex(l => l.includes("function setCookiesFromHeaders"));
for (let j = i; j < i + 18; j++) console.log(j + 1, lines[j]);
console.log("---- invalidatePreparedChatSession ----");
i = lines.findIndex(l => l.includes("async invalidatePreparedChatSession"));
for (let j = i; j < i + 16; j++) console.log(j + 1, lines[j]);
console.log("---- constructor ----");
i = lines.findIndex(l => /^\s{2}constructor\(\{/.test(l));
for (let j = i; j < i + 60; j++) console.log(j + 1, lines[j]);
console.log("---- normalizeProxyUrl ----");
s = readFileSync("src/proxy.js", "utf8");
lines = s.split("\n");
i = lines.findIndex(l => l.includes("export function normalizeProxyUrl"));
for (let j = i; j < i + 12; j++) console.log(j + 1, lines[j]);
